### ISSUE TITLE
请问yolo的版本是哪个版本呢

### ISSUE THREAD

**Issue by Xyxx3353** [lsewcx/yolov52onnx#1]
请问yolo的版本是哪个版本呢，后续导出onnx需要做哪些操作呢

**Comment by lsewcx** [comment]
yolov5的版本还没测试其他的版本怎么样，pt转onnx就按照官方的文档转就行

**Comment by Xyxx3353** [comment]
在python3.10 yolov5 0.6 opset=13复现成功了，感谢分享，已star

**Comment by lsewcx** [comment]
非常激动能帮到你 @Xyxx3353 谢谢你使用我代码
